TARGET_BOARD_PLATFORM := mt6577
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
ARCH_ARM_HAVE_VFP := true
TARGET_CPU_SMP := true
TARGET_ARCH := arm
ARCH_ARM_HAVE_NEON := true
TARGET_NO_BOOTLOADER := true
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_ARCH_VARIANT_CPU := cortex-a9
TARGET_CPU_VARIANT := cortex-a9
TARGET_NO_FACTORYIMAGE := true

BOARD_BOOTIMAGE_PARTITION_SIZE := 0x00600000
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x00600000
BOARD_CACHEIMAGE_PARTITION_SIZE := 393216000
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 680525824
BOARD_USERDATAIMAGE_PARTITION_SIZE := 3270508544

# Kernel
BOARD_KERNEL_CMDLINE := 
BOARD_KERNEL_BASE := 0x10000000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_FLASH_BLOCK_SIZE := 131072
BOARD_CUSTOM_BOOTIMG := true
BOARD_CUSTOM_BOOTIMG_MK := device/lenovo/huaqin17/boot.mk
# HACK: clean kernel folder instead of using config
TARGET_KERNEL_CONFIG := clean
TARGET_KERNEL_SOURCE := kernel/lenovo/huaqin17/kernel
BOARD_MKBOOTIMG_ARGS += --ramdisk_offset 0x01000000 --tags_offset 0x00000100

BOARD_HAS_NO_SELECT_BUTTON := true
BOARD_SDCARD_INTERNAL_DEVICE := /dev/block/mmcblk1p1

TARGET_GLOBAL_CFLAGS += -DMR0_AUDIO_BLOB -DDISABLE_HW_ID_MATCH_CHECK -DMR0_CAMERA_BLOB -DNEEDS_VECTORIMPL_SYMBOLS -DMTK_COMBO_SUPPORT
TARGET_GLOBAL_CPPFLAGS += -DMR0_AUDIO_BLOB -DDISABLE_HW_ID_MATCH_CHECK -DMR0_CAMERA_BLOB -DNEEDS_VECTORIMPL_SYMBOLS -DMTK_COMBO_SUPPORT
BOARD_HAVE_PRE_KITKAT_AUDIO_BLOB := true
BOARD_HAVE_PRE_KITKAT_AUDIO_POLICY_BLOB := true
BOARD_NEEDS_OLD_HWC_API := true
TARGET_RUNNING_WITHOUT_SYNC_FRAMEWORK := true

TARGET_GLOBAL_CFLAGS += -mfpu=neon -mfloat-abi=softfp
TARGET_GLOBAL_CPPFLAGS += -mfpu=neon -mfloat-abi=softfp
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_SPARSE_EXT_DISABLED := false
USE_CAMERA_STUB := true

# EGL
BOARD_EGL_CFG := device/lenovo/huaqin17/egl.cfg
USE_OPENGL_RENDERER := true
BOARD_EGL_WORKAROUND_BUG_10194508 := true
TARGET_DISABLE_SURFACEFLINGER_PBUFFERS := true

# Wifi
WPA_SUPPLICANT_VERSION := VER_0_8_X
BOARD_WPA_SUPPLICANT_DRIVER := NL80211
BOARD_HOSTAPD_DRIVER := NL80211
BOARD_WLAN_DEVICE := mediatek
BOARD_WPA_SUPPLICANT_PRIVATE_LIB := lib_driver_cmd_mtk
BOARD_HOSTAPD_PRIVATE_LIB   := lib_driver_cmd_mtk
WIFI_DRIVER_FW_PATH_PARAM:="/dev/wmtWifi"
WIFI_DRIVER_FW_PATH_STA:=STA
WIFI_DRIVER_FW_PATH_AP:=AP
WIFI_DRIVER_FW_PATH_P2P:=P2P

# BT
BOARD_HAVE_BLUETOOTH := true
BOARD_HAVE_BLUETOOTH_MTK := true
BOARD_BLUETOOTH_DOES_NOT_USE_RFKILL := true
BOARD_BLUETOOTH_BDROID_BUILDCFG_INCLUDE_DIR := device/lenovo/huaqin17/bluetooth
BOARD_CONNECTIVITY_MODULE := combo_mt66xx
BOARD_CONNECTIVITY_VENDOR := MediaTek

# GPS
BOARD_MEDIATEK_USES_GPS := true
BOARD_GPS_LIBRARIES := libgps_mtk

# FM
MTK_FM_CHIP := MT6628_FM

# TWRP stuff

TARGET_RECOVERY_FSTAB := device/lenovo/huaqin17/recovery.fstab
TARGET_USE_CUSTOM_LUN_FILE_PATH := /sys/devices/platform/mt_usb/gadget/lun%d/file
TW_BRIGHTNESS_PATH := /sys/class/leds/lcd-backlight/brightness
DEVICE_RESOLUTION := 1024x600
RECOVERY_GRAPHICS_USE_LINELENGTH := true
TW_USE_MODEL_HARDWARE_ID_FOR_DEVICE_ID := true
TW_INTERNAL_STORAGE_PATH :="/sdcard"
TW_INTERNAL_STORAGE_MOUNT_POINT :="sdcard"
TW_EXTERNAL_STORAGE_PATH :="/sdcard2"
TW_EXTERNAL_STORAGE_MOUNT_POINT :="sdcard2"
SP1_NAME := "uboot"
SP1_BACKUP_METHOD := image
SP1_MOUNTABLE := 0
SP2_NAME := "nvram"
SP2_DISPLAY_NAME := "nvram"
SP2_BACKUP_METHOD := image
SP2_MOUNTABLE := 0

